version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ngo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: NgoDb
    ports:
      - "5432:5432"
    restart: unless-stopped
